# Site settings
title: The Open Data Handbook
short_title: Open Data Handbook
email: admin@okfn.org
description: > # this means to ignore newlines until "baseurl:"
  A collection of research, resources, use cases and guides for civil society and government on the “what, why & how” of open data. 
baseurl: ""
url: "http://new.opendatahandbook.org" # the base hostname & protocol for your site
github_username:  okfn
github_repo:  opendatahandbook-v2

devs:
  -
      name: Sam Smith
      github: mintcanary
  -
      name: Rufus Pollock
      github: rgrp
  -
      name: Paul Walsh
      github: pwalsh
      

supporters:
  -
    name: Shuttleworth Foundation
    logo: shuttleworth.png
    footer_logo: shuttleworth-footer.png
    url: https://www.shuttleworthfoundation.org/
  -
    name: The World Bank
    logo: worldbank.png
    footer_logo: worldbank-footer.png
    url: http://www.worldbank.org/
    
      
#googleanalytics: UA-XXXXX-X

# Build settings
markdown: kramdown

permalink: pretty

collections:
  resources:
    output: true
    has_translation: false
    title: Open Data Resources
    filters:
      - Topic
      - Language
      - Region
      - MediaType
  value-stories:
    output: true
    has_translation: true
    title: Open Data Value Stories
  glossary:
    output: true
    has_translation: true
    title: Open Data Glossary
  guide:
    output: true
    has_translation: true
    title: Open Data Handbook
    toc:
      entry_point: 'introduction'
      chapters:
        - title: 'Introduction'
          slug: 'introduction'
          sections:
            - title: 'Target Audience'
              slug: 'target-audience'
            - title: 'Credits'
              slug: 'credits'
        - title: 'Why Open Data?'
          slug: 'why-open-data'
        - title: 'What is Open Data?'
          slug: 'what-is-open-data'

defaults:
#en
  -
    scope: #this should be removed once more specific paths are defined
      path: ""
    values:
      section: Guide
      layout: page
      edit: true
  -
    scope:
      path: "en"
    values:
      lang: en
  -
    scope:
      path: "en/guide"
    values:
      section: Guide
      layout: page
      edit: true
  -
    scope:
      path: "contribute"
    values:
      section: Contribute
      layout: docs
      edit: true
  -
    scope:
      type: "posts"
    values:
      section: Value Stories
      permalink: /value-stories/:title/
      layout: post
      edit: true
#de
  -
    scope:
      path: "de"
    values:
      lang: de
  -
    scope:
      path: "de/guide"
    values:
      section: Guide
      layout: page
      edit: true