# Site settings
title: Open Data Handbook
email: admin@okfn.org
description: > # this means to ignore newlines until "baseurl:"
  This handbook introduces you to the legal, social and technical aspects of open data. It can be used by anyone but is especially useful for those working with government data. It discusses the why, what and how of open data – why to go open, what open is, and the how to do open.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://new.opendatahandbook.org" # the base hostname & protocol for your site
github_username:  okfn
github_repo:  opendatahandbook-v2

# Build settings
markdown: kramdown

permalink: pretty

defaults: 
  - 
    scope: 
      path: "en" 
    values: 
      section: Open Data Handbook
      layout: page
      lang: en
      extension: md
  - 
    scope: 
      path: "contribute" 
    values: 
      section: Contribute
      layout: docs
  - 
    scope: 
      type: "posts"
    values:
      section: Value Stories
      permalink: /value-stories/:title
      layout: post
