# Site settings
title: Open Data Handbook
email: admin@okfn.org
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eleifend metus eget justo tincidunt, nec consequat turpis pretium. Etiam varius tellus tortor, in mattis ex convallis vel.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://new.opendatahandbook.org" # the base hostname & protocol for your site
github_username:  okfn
github_repo:  opendatahandbook-v2

# Build settings
markdown: kramdown

permalink: pretty

defaults: 
  - 
    scope: 
      path: "en" 
    values: 
      section: Open Data Handbook
      layout: page
      lang: en
      edit: true
  - 
    scope: 
      path: "contribute" 
    values: 
      section: Contribute
      layout: docs
      edit: true
  - 
    scope: 
      type: "posts"
    values:
      section: Value Stories
      permalink: /value-stories/:title
      layout: post
      edit: true
